export const DEPENDENTS_TABLE = 'dependents';

export const DEPENDENTS_FIELDS = {
  DEPENDENT_ID: 'dependent_id',
  USER_ID: 'user_id',
  RELATION_ID: 'relation_id',
  PHONE_NUMBER: 'phone_number',
  FULL_NAME: 'full_name',
  DOB: 'dob',
  GENDER: 'gender',
  COUNTRY: 'country',
  ADDRESS: 'address',
  CONTACT_NO: 'contact_no',
  MATERIAL_STATUS: 'material_status',
  DO_YOU_HAVE_CHILDREN: 'do_you_have_children',
  HOW_MANY_CHILDREN: 'how_many_children',
  ARE_YOU_PREGNANT: 'are_you_pregnant',
  PREGNANCY_DETAIL: 'pregnancy_detail',
  PROFILE_COMPLETED: 'profile_completed',
  IMAGE: 'image',
  CREATED_AT: 'created_at',
  UPDATED_AT: 'updated_at',
  IS_ACTIVE: 'is_active'
};

export const DEPENDENTS_CREATE_TABLE_SQL = `
  CREATE TABLE IF NOT EXISTS ${DEPENDENTS_TABLE} (
    ${DEPENDENTS_FIELDS.DEPENDENT_ID} INT PRIMARY KEY AUTO_INCREMENT,
    ${DEPENDENTS_FIELDS.USER_ID} INT NOT NULL,
    ${DEPENDENTS_FIELDS.RELATION_ID} INT,
    ${DEPENDENTS_FIELDS.PHONE_NUMBER} VARCHAR(20),
    ${DEPENDENTS_FIELDS.FULL_NAME} VARCHAR(100),
    ${DEPENDENTS_FIELDS.DOB} DATE,
    ${DEPENDENTS_FIELDS.GENDER} ENUM('male','female','other'),
    ${DEPENDENTS_FIELDS.COUNTRY} VARCHAR(50),
    ${DEPENDENTS_FIELDS.ADDRESS} TEXT,
    ${DEPENDENTS_FIELDS.CONTACT_NO} VARCHAR(20),
    ${DEPENDENTS_FIELDS.MATERIAL_STATUS} ENUM('single','married','divorced','widowed'),
    ${DEPENDENTS_FIELDS.DO_YOU_HAVE_CHILDREN} TINYINT(1) DEFAULT 0,
    ${DEPENDENTS_FIELDS.HOW_MANY_CHILDREN} INT DEFAULT 0,
    ${DEPENDENTS_FIELDS.ARE_YOU_PREGNANT} TINYINT(1) DEFAULT 0,
    ${DEPENDENTS_FIELDS.PREGNANCY_DETAIL} TEXT,
    ${DEPENDENTS_FIELDS.PROFILE_COMPLETED} TINYINT(1) DEFAULT 0,
    ${DEPENDENTS_FIELDS.IMAGE} VARCHAR(255),
    ${DEPENDENTS_FIELDS.CREATED_AT} TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ${DEPENDENTS_FIELDS.UPDATED_AT} TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ${DEPENDENTS_FIELDS.IS_ACTIVE} TINYINT(1) DEFAULT 1,
    FOREIGN KEY (${DEPENDENTS_FIELDS.USER_ID}) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (${DEPENDENTS_FIELDS.RELATION_ID}) REFERENCES relationships(id) ON DELETE SET NULL
  )
`;

export const DEPENDENTS_MESSAGES = {
  DEPENDENT_ADDED: 'Dependent added successfully',
  DEPENDENT_UPDATED: 'Dependent updated successfully',
  DEPENDENT_DELETED: 'Dependent deleted successfully',
  DEPENDENT_NOT_FOUND: 'Dependent not found',
  DEPENDENTS_FETCHED: 'Dependents fetched successfully',
  INVALID_DEPENDENT_DATA: 'Invalid dependent data',
  DEPENDENT_ALREADY_EXISTS: 'Dependent already exists'
};
