export const VACCINES_TABLE = 'vaccines';

export const VACCINES_SCHEMA = `
  CREATE TABLE IF NOT EXISTS ${VACCINES_TABLE} (
    vaccine_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL,
    sub_category VARCHAR(50) NOT NULL,
    min_age_months INT NOT NULL DEFAULT 0,
    max_age_months INT NULL,
    total_doses INT NULL,
    frequency VARCHAR(200) NOT NULL,
    when_to_give TEXT NULL,
    dose VARCHAR(200) NULL,
    route VARCHAR(100) NULL,
    site VARCHAR(150) NULL,
    notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    INDEX idx_vaccine_name (name),
    INDEX idx_vaccine_type (type),
    INDEX idx_vaccine_category (category),
    INDEX idx_vaccine_sub_category (sub_category),
    INDEX idx_age_range (min_age_months, max_age_months)
  )
`;

export const VACCINES_FIELDS = {
  VACCINE_ID: 'vaccine_id',
  NAME: 'name',
  TYPE: 'type',
  CATEGORY: 'category',
  SUB_CATEGORY: 'sub_category',
  MIN_AGE_MONTHS: 'min_age_months',
  MAX_AGE_MONTHS: 'max_age_months',
  TOTAL_DOSES: 'total_doses',
  FREQUENCY: 'frequency',
  WHEN_TO_GIVE: 'when_to_give',
  DOSE: 'dose',
  ROUTE: 'route',
  SITE: 'site',
  NOTES: 'notes',
  CREATED_AT: 'created_at',
  UPDATED_AT: 'updated_at',
  IS_ACTIVE: 'is_active'
};

export const VACCINES_DATA = [
  // BIRTH TO 1 YEAR VACCINES
  {
    vaccine_id: 1,
    name: "BCG",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 0,
    max_age_months: 12,
    total_doses: 1,
    frequency: "One time",
    when_to_give: "At birth or up to 1 year",
    dose: "0.1 ml (0.05 ml if <1 month)",
    route: "Intradermal",
    site: "Left Upper Arm",
    notes: "Prevents severe TB forms."
  },
  {
    vaccine_id: 2,
    name: "Hepatitis B (Birth Dose)",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 0,
    max_age_months: 1,
    total_doses: 1,
    frequency: "Within 24 hours of birth",
    when_to_give: "Within 24 hours of birth",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Anterolateral mid-thigh",
    notes: "Prevents mother-to-child transmission."
  },
  {
    vaccine_id: 3,
    name: "OPV-0",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 0,
    max_age_months: 1,
    total_doses: 1,
    frequency: "Within 15 days of birth",
    when_to_give: "Within 15 days of birth",
    dose: "2 drops",
    route: "Oral",
    site: "Oral",
    notes: "Zero-dose protection for polio."
  },
  {
    vaccine_id: 4,
    name: "OPV-1,2,3",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 1.5,
    max_age_months: 3.5,
    total_doses: 3,
    frequency: "Primary series",
    when_to_give: "6, 10, 14 weeks",
    dose: "2 drops each",
    route: "Oral",
    site: "Oral",
    notes: "Part of polio eradication program."
  },
  {
    vaccine_id: 5,
    name: "Pentavalent-1,2,3 (DPT-HepB-Hib)",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 1.5,
    max_age_months: 3.5,
    total_doses: 3,
    frequency: "Primary series",
    when_to_give: "6, 10, 14 weeks",
    dose: "0.5 ml each",
    route: "Intramuscular",
    site: "Anterolateral mid-thigh",
    notes: "Covers Diphtheria, Pertussis, Tetanus, HepB, Hib."
  },
  {
    vaccine_id: 6,
    name: "Rotavirus Vaccine (RVV)-1,2,3",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 1.5,
    max_age_months: 3.5,
    total_doses: 3,
    frequency: "Primary series",
    when_to_give: "6, 10, 14 weeks",
    dose: "5 drops each",
    route: "Oral",
    site: "Oral",
    notes: "Prevents severe diarrhea; available in select states."
  },
  {
    vaccine_id: 7,
    name: "fIPV-1,2",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 1.5,
    max_age_months: 3.5,
    total_doses: 2,
    frequency: "Primary series",
    when_to_give: "6 and 14 weeks",
    dose: "0.1 ml each",
    route: "Intradermal",
    site: "Right Upper Arm",
    notes: "Enhances polio immunity."
  },
  {
    vaccine_id: 8,
    name: "PCV-1,2 (Pneumococcal)",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 1.5,
    max_age_months: 3.5,
    total_doses: 2,
    frequency: "Primary series",
    when_to_give: "6 and 14 weeks",
    dose: "0.5 ml each",
    route: "Intramuscular",
    site: "Anterolateral mid-thigh",
    notes: "Prevents pneumonia; booster at 9–12 months."
  },
  {
    vaccine_id: 9,
    name: "Measles/MR-1",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 9,
    max_age_months: 12,
    total_doses: 1,
    frequency: "Primary dose",
    when_to_give: "9–12 months",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Right Upper Arm",
    notes: "Prevents measles & rubella."
  },
  {
    vaccine_id: 10,
    name: "JE-1 (Japanese Encephalitis)",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 9,
    max_age_months: 12,
    total_doses: 1,
    frequency: "Primary dose",
    when_to_give: "9–12 months",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Left Upper Arm",
    notes: "Mandatory in endemic districts."
  },
  {
    vaccine_id: 11,
    name: "Vitamin A (1st Dose)",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 9,
    max_age_months: 12,
    total_doses: 1,
    frequency: "9 months with MR",
    when_to_give: "9 months with MR",
    dose: "1 ml (1 lakh IU)",
    route: "Oral",
    site: "Oral",
    notes: "Prevents vitamin A deficiency."
  },
  {
    vaccine_id: 12,
    name: "Typhoid Conjugate (Optional)",
    type: "Optional",
    category: "Infant",
    sub_category: "Optional",
    min_age_months: 6,
    max_age_months: 9,
    total_doses: 1,
    frequency: "Single dose",
    when_to_give: "6–9 months",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Anterolateral mid-thigh",
    notes: "Single dose; IAP recommended."
  },
  {
    vaccine_id: 13,
    name: "Influenza (Optional)",
    type: "Optional",
    category: "Infant",
    sub_category: "Optional",
    min_age_months: 6,
    max_age_months: 1200,
    total_doses: 1,
    frequency: "Annually",
    when_to_give: "From 6 months, annually",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "For high-risk infants (<9 years get 2 doses first year)."
  },

  // 1-5 YEARS VACCINES
  {
    vaccine_id: 14,
    name: "DPT Booster-1",
    type: "Mandatory",
    category: "Child",
    sub_category: "Mandatory",
    min_age_months: 16,
    max_age_months: 24,
    total_doses: 1,
    frequency: "First booster",
    when_to_give: "16–24 months",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Anterolateral mid-thigh",
    notes: "Mandatory."
  },
  {
    vaccine_id: 15,
    name: "Measles/MR-2",
    type: "Mandatory",
    category: "Child",
    sub_category: "Mandatory",
    min_age_months: 16,
    max_age_months: 24,
    total_doses: 1,
    frequency: "Second dose",
    when_to_give: "16–24 months",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Right Upper Arm",
    notes: "Mandatory; part of phased rollout."
  },
  {
    vaccine_id: 16,
    name: "OPV Booster",
    type: "Mandatory",
    category: "Child",
    sub_category: "Mandatory",
    min_age_months: 16,
    max_age_months: 24,
    total_doses: 1,
    frequency: "Booster",
    when_to_give: "16–24 months",
    dose: "2 drops",
    route: "Oral",
    site: "Oral",
    notes: "Mandatory."
  },
  {
    vaccine_id: 17,
    name: "JE-2",
    type: "Mandatory",
    category: "Child",
    sub_category: "Mandatory",
    min_age_months: 16,
    max_age_months: 24,
    total_doses: 1,
    frequency: "Second dose",
    when_to_give: "16–24 months",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Left Upper Arm",
    notes: "For endemic areas."
  },
  {
    vaccine_id: 18,
    name: "Vitamin A (2–9 Doses)",
    type: "Mandatory",
    category: "Child",
    sub_category: "Mandatory",
    min_age_months: 9,
    max_age_months: 60,
    total_doses: 9,
    frequency: "Every 6 months up to 5 years",
    when_to_give: "Every 6 months up to 5 years",
    dose: "2 ml (2 lakh IU)",
    route: "Oral",
    site: "Oral",
    notes: "Total 9 doses recommended."
  },
  {
    vaccine_id: 19,
    name: "DPT Booster-2",
    type: "Mandatory",
    category: "Child",
    sub_category: "Mandatory",
    min_age_months: 60,
    max_age_months: 72,
    total_doses: 1,
    frequency: "Second booster",
    when_to_give: "5–6 years",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Mandatory."
  },
  {
    vaccine_id: 20,
    name: "MMR (Optional)",
    type: "Optional",
    category: "Child",
    sub_category: "Optional",
    min_age_months: 15,
    max_age_months: 60,
    total_doses: 2,
    frequency: "2 doses for mumps protection",
    when_to_give: "15 months & 5 years",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "2 doses for mumps protection."
  },
  {
    vaccine_id: 21,
    name: "Varicella (Optional)",
    type: "Optional",
    category: "Child",
    sub_category: "Optional",
    min_age_months: 15,
    max_age_months: 72,
    total_doses: 2,
    frequency: "2 doses",
    when_to_give: "15 months & 4–6 years",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "Prevents chickenpox; 2 doses."
  },
  {
    vaccine_id: 22,
    name: "Hepatitis A (Optional)",
    type: "Optional",
    category: "Child",
    sub_category: "Optional",
    min_age_months: 12,
    max_age_months: 23,
    total_doses: 2,
    frequency: "2 doses, 6 months apart",
    when_to_give: "12–23 months",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "2 doses, 6 months apart."
  },

  // 6-18 YEARS VACCINES
  {
    vaccine_id: 23,
    name: "Tdap/Td",
    type: "Mandatory",
    category: "Adolescent",
    sub_category: "Mandatory",
    min_age_months: 120,
    max_age_months: 192,
    total_doses: 2,
    frequency: "At 10 and 16 years",
    when_to_give: "10 years & 16 years",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Mandatory Td; IAP prefers Tdap for pertussis."
  },
  {
    vaccine_id: 24,
    name: "HPV",
    type: "Optional",
    category: "Adolescent",
    sub_category: "Optional",
    min_age_months: 108,
    max_age_months: 168,
    total_doses: 2,
    frequency: "2 doses, 6 months apart",
    when_to_give: "9–14 years",
    dose: "0.5 ml (2 doses, 6 months apart)",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "3 doses if >15 years or immunocompromised."
  },
  {
    vaccine_id: 25,
    name: "Typhoid (Booster)",
    type: "Optional",
    category: "Adolescent",
    sub_category: "Optional",
    min_age_months: 72,
    max_age_months: 1200,
    total_doses: null,
    frequency: "Every 3 years",
    when_to_give: "Every 3 years",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Conjugate preferred."
  },
  {
    vaccine_id: 26,
    name: "Influenza",
    type: "Optional",
    category: "Adolescent",
    sub_category: "Optional",
    min_age_months: 6,
    max_age_months: 1200,
    total_doses: 1,
    frequency: "Annually",
    when_to_give: "Annually",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "For high-risk adolescents."
  },
  {
    vaccine_id: 27,
    name: "Catch-up (e.g., Hep B, MMR)",
    type: "Mandatory",
    category: "Adolescent",
    sub_category: "Mandatory",
    min_age_months: 120,
    max_age_months: 216,
    total_doses: 1,
    frequency: "As needed",
    when_to_give: "If missed earlier",
    dose: "Varies",
    route: "Varies",
    site: "Varies",
    notes: "Complete missed immunizations."
  },

  // 18-60 YEARS VACCINES
  {
    vaccine_id: 28,
    name: "Td/Tdap Booster",
    type: "Mandatory",
    category: "Adult",
    sub_category: "Mandatory",
    min_age_months: 216,
    max_age_months: 720,
    total_doses: null,
    frequency: "Every 10 years",
    when_to_give: "Every 10 years",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Maintain tetanus/diphtheria immunity."
  },
  {
    vaccine_id: 29,
    name: "Influenza",
    type: "Mandatory",
    category: "Adult",
    sub_category: "Mandatory",
    min_age_months: 216,
    max_age_months: 720,
    total_doses: 1,
    frequency: "Annually",
    when_to_give: "Annually",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "For high-risk adults."
  },
  {
    vaccine_id: 30,
    name: "Pneumococcal (PCV13/15 + PPSV23)",
    type: "High-risk",
    category: "Adult",
    sub_category: "High-risk",
    min_age_months: 228,
    max_age_months: 768,
    total_doses: 2,
    frequency: "Once at 19-64 if high-risk",
    when_to_give: "Once at 19–64 if high-risk",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Sequential; for chronic or immune conditions."
  },
  {
    vaccine_id: 31,
    name: "HPV",
    type: "Optional",
    category: "Adult",
    sub_category: "Optional",
    min_age_months: 216,
    max_age_months: 540,
    total_doses: 3,
    frequency: "Up to 26 years (males), 45 years (females)",
    when_to_give: "Up to 26 years (males), 45 years (females)",
    dose: "0.5 ml (2-3 doses)",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Prevents cervical & HPV-related cancers."
  },
  {
    vaccine_id: 32,
    name: "Hepatitis B",
    type: "High-risk",
    category: "Adult",
    sub_category: "High-risk",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 3,
    frequency: "If unvaccinated/high-risk",
    when_to_give: "If unvaccinated/high-risk",
    dose: "0.5 ml (3 doses)",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "For healthcare workers, dialysis, etc."
  },
  {
    vaccine_id: 33,
    name: "Hepatitis A",
    type: "High-risk",
    category: "Adult",
    sub_category: "High-risk",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "High-risk groups",
    when_to_give: "High-risk groups",
    dose: "0.5 ml (2 doses)",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "For travelers or liver disease."
  },
  {
    vaccine_id: 34,
    name: "MMR",
    type: "High-risk",
    category: "Adult",
    sub_category: "High-risk",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "If no immunity",
    when_to_give: "If no immunity",
    dose: "0.5 ml (1–2 doses)",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "For outbreaks or travel."
  },
  {
    vaccine_id: 35,
    name: "Varicella",
    type: "High-risk",
    category: "Adult",
    sub_category: "High-risk",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "If no prior infection",
    when_to_give: "If no prior infection",
    dose: "0.5 ml (2 doses)",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "Prevents chickenpox."
  },
  {
    vaccine_id: 36,
    name: "Cholera (Oral)",
    type: "High-risk",
    category: "Adult",
    sub_category: "High-risk",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 0,
    frequency: "In endemic areas/outbreaks",
    when_to_give: "In endemic areas/outbreaks",
    dose: "Varies",
    route: "Oral",
    site: "Oral",
    notes: "High-risk only."
  },

  // 60+ YEARS VACCINES
  {
    vaccine_id: 37,
    name: "Influenza",
    type: "Mandatory",
    category: "Elderly",
    sub_category: "Mandatory",
    min_age_months: 720,
    max_age_months: 1200,
    total_doses: 1,
    frequency: "Annually",
    when_to_give: "Annually",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Strongly recommended for all >60."
  },
  {
    vaccine_id: 38,
    name: "Pneumococcal (PCV13/15 + PPSV23)",
    type: "Mandatory",
    category: "Elderly",
    sub_category: "Mandatory",
    min_age_months: 780,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "Once at >65; booster if needed",
    when_to_give: "Once at >65; booster if needed",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Revaccinate PPSV23 after 5 years if high-risk."
  },
  {
    vaccine_id: 39,
    name: "Herpes Zoster (Shingles)",
    type: "Optional",
    category: "Elderly",
    sub_category: "Optional",
    min_age_months: 600,
    max_age_months: 1200,
    total_doses: 2,
    frequency: ">50 years (once)",
    when_to_give: ">50 years (once)",
    dose: "0.5 ml (2 doses, 2–6 months apart)",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Prevents shingles & post-herpetic pain."
  },
  {
    vaccine_id: 40,
    name: "Td/Tdap Booster",
    type: "Mandatory",
    category: "Elderly",
    sub_category: "Mandatory",
    min_age_months: 720,
    max_age_months: 1200,
    total_doses: null,
    frequency: "Every 10 years",
    when_to_give: "Every 10 years",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Maintain tetanus/diphtheria immunity."
  },
  {
    vaccine_id: 41,
    name: "Hepatitis B",
    type: "High-risk",
    category: "Elderly",
    sub_category: "High-risk",
    min_age_months: 720,
    max_age_months: 1200,
    total_doses: 3,
    frequency: "If high-risk & unvaccinated",
    when_to_give: "If high-risk & unvaccinated",
    dose: "0.5 ml (3 doses)",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "For chronic illness."
  },

  // TRAVEL VACCINES
  {
    vaccine_id: 42,
    name: "Yellow Fever",
    type: "Travel",
    category: "Travel",
    sub_category: "Mandatory",
    min_age_months: 9,
    max_age_months: 1200,
    total_doses: 1,
    frequency: "One time",
    when_to_give: "≥10 days before travel",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Arm",
    notes: "Required for entry to endemic countries."
  },
  {
    vaccine_id: 43,
    name: "Polio (OPV/IPV Booster)",
    type: "Travel",
    category: "Travel",
    sub_category: "Mandatory",
    min_age_months: 0,
    max_age_months: 1200,
    total_doses: 1,
    frequency: "4 weeks–12 months before travel",
    when_to_give: "4 weeks–12 months before travel",
    dose: "2 drops or 0.5 ml",
    route: "Oral / Intramuscular",
    site: "Oral / Arm",
    notes: "For travel to countries with ongoing polio."
  },
  {
    vaccine_id: 44,
    name: "Meningococcal (ACYW-135)",
    type: "Travel",
    category: "Travel",
    sub_category: "Mandatory",
    min_age_months: 9,
    max_age_months: 1200,
    total_doses: 1,
    frequency: "≥10 days before travel",
    when_to_give: "≥10 days before travel",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Mandatory for Hajj/Umrah pilgrims."
  },
  {
    vaccine_id: 45,
    name: "Hepatitis A/B",
    type: "Travel",
    category: "Travel",
    sub_category: "Optional",
    min_age_months: 0,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "2–3 doses before travel",
    when_to_give: "2–3 doses before travel",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "For travelers to risk regions."
  },
  {
    vaccine_id: 46,
    name: "Typhoid",
    type: "Travel",
    category: "Travel",
    sub_category: "Optional",
    min_age_months: 0,
    max_age_months: 1200,
    total_doses: 1,
    frequency: "2 weeks before travel",
    when_to_give: "2 weeks before travel",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Food/water protection."
  },
  {
    vaccine_id: 47,
    name: "Rabies",
    type: "Travel",
    category: "Travel",
    sub_category: "Optional",
    min_age_months: 0,
    max_age_months: 1200,
    total_doses: 3,
    frequency: "Pre-exposure 0,7,21 days",
    when_to_give: "Pre-exposure 0,7,21 days",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "For animal exposure risk."
  },
  {
    vaccine_id: 48,
    name: "Japanese Encephalitis",
    type: "Travel",
    category: "Travel",
    sub_category: "Optional",
    min_age_months: 0,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "2 doses, 28 days apart",
    when_to_give: "2 doses, 28 days apart",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "For Asia travelers or endemic regions."
  }
];