export const VACCINES_TABLE = 'vaccines';

export const VACCINES_SCHEMA = `
  CREATE TABLE IF NOT EXISTS ${VACCINES_TABLE} (
    vaccine_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL,
    sub_category VARCHAR(50) NOT NULL,
    min_age_months INT NOT NULL DEFAULT 0,
    max_age_months INT NULL,
    total_doses INT NULL,
    frequency VARCHAR(200) NOT NULL,
    when_to_give TEXT NULL,
    dose VARCHAR(200) NULL,
    route VARCHAR(100) NULL,
    site VARCHAR(150) NULL,
    notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    INDEX idx_vaccine_name (name),
    INDEX idx_vaccine_type (type),
    INDEX idx_vaccine_category (category),
    INDEX idx_vaccine_sub_category (sub_category),
    INDEX idx_age_range (min_age_months, max_age_months)
  )
`;

export const VACCINES_FIELDS = {
  VACCINE_ID: 'vaccine_id',
  NAME: 'name',
  TYPE: 'type',
  CATEGORY: 'category',
  SUB_CATEGORY: 'sub_category',
  MIN_AGE_MONTHS: 'min_age_months',
  MAX_AGE_MONTHS: 'max_age_months',
  TOTAL_DOSES: 'total_doses',
  FREQUENCY: 'frequency',
  WHEN_TO_GIVE: 'when_to_give',
  DOSE: 'dose',
  ROUTE: 'route',
  SITE: 'site',
  NOTES: 'notes',
  CREATED_AT: 'created_at',
  UPDATED_AT: 'updated_at',
  IS_ACTIVE: 'is_active'
};

export const VACCINES_DATA = [
  // PRENATAL VACCINES
  {
    vaccine_id: 1,
    name: "Tetanus Toxoid (TT-1)",
    type: "Mandatory",
    category: "Prenatal",
    sub_category: "Mandatory",
    min_age_months: -9,
    max_age_months: 0,
    total_doses: 1,
    frequency: "Early pregnancy",
    when_to_give: "Early in pregnancy",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Mandatory under NIS. Protects against maternal and neonatal tetanus"
  },
  {
    vaccine_id: 2,
    name: "Hepatitis B",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 0,
    max_age_months: 1,
    total_doses: 1,
    frequency: "Within 24 hours of birth",
    when_to_give: "Within 24 hours of birth",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Antero-lateral thigh (infants), Deltoid (older children/adults)",
    notes: "Mandatory; prevents mother-to-child transmission"
  },
  {
    vaccine_id: 3,
    name: "Tetanus Toxoid (TT-Booster)",
    type: "Mandatory",
    category: "Prenatal",
    sub_category: "Mandatory",
    min_age_months: -3,
    max_age_months: 0,
    total_doses: 1,
    frequency: "If 2 TT doses in last 3 years",
    when_to_give: "If 2 TT doses received in pregnancy within last 3 years",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Single dose for recent pregnancies"
  },
  {
    vaccine_id: 4,
    name: "Influenza (IIV) - Prenatal",
    type: "Optional",
    category: "Prenatal",
    sub_category: "Optional",
    min_age_months: -9,
    max_age_months: 0,
    total_doses: 1,
    frequency: "Any trimester",
    when_to_give: "Any trimester (IAP recommendation)",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Optional; recommended for all pregnant women annually, especially in flu season"
  },

  // BIRTH TO 1 YEAR VACCINES
  {
    vaccine_id: 5,
    name: "BCG",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 0,
    max_age_months: 1,
    total_doses: 1,
    frequency: "One time",
    when_to_give: "At birth or as early as possible till 1 year",
    dose: "0.1 ml (0.05 ml if age < 1 month)",
    route: "Intradermal",
    site: "Left Upper Arm",
    notes: "Prevents severe forms of childhood TB"
  },
  {
    vaccine_id: 6,
    name: "OPV-0",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 0,
    max_age_months: 0.5,
    total_doses: 1,
    frequency: "Birth dose",
    when_to_give: "Within 15 days of birth",
    dose: "2 drops",
    route: "Oral",
    site: "Oral",
    notes: "Mandatory; zero-dose polio protection"
  },
  {
    vaccine_id: 7,
    name: "OPV-1,2,3",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 1.5,
    max_age_months: 3.5,
    total_doses: 3,
    frequency: "Primary series",
    when_to_give: "6, 10, 14 weeks (up to 5 years)",
    dose: "2 drops each",
    route: "Oral",
    site: "Oral",
    notes: "Mandatory; part of polio eradication"
  },
  {
    vaccine_id: 8,
    name: "Pentavalent-1,2,3 (DPT-HepB-Hib)",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 1.5,
    max_age_months: 3.5,
    total_doses: 3,
    frequency: "Primary series",
    when_to_give: "6, 10, 14 weeks (up to 1 year)",
    dose: "0.5 ml each",
    route: "Intramuscular",
    site: "Antero-lateral mid-thigh",
    notes: "Mandatory; covers diphtheria, pertussis, tetanus, HepB, Hib"
  },
  {
    vaccine_id: 9,
    name: "Rotavirus Vaccine (RVV)-1,2,3",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 1.5,
    max_age_months: 3.5,
    total_doses: 3,
    frequency: "Primary series",
    when_to_give: "6, 10, 14 weeks (up to 1 year)",
    dose: "5 drops each",
    route: "Oral",
    site: "Oral",
    notes: "Mandatory in phased areas; prevents severe diarrhea. Available in select states like Andhra Pradesh, Haryana"
  },
  {
    vaccine_id: 10,
    name: "fIPV-1,2 (Fractional Inactivated Polio Vaccine)",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 1.5,
    max_age_months: 3.5,
    total_doses: 2,
    frequency: "Primary series",
    when_to_give: "6 and 14 weeks",
    dose: "0.1 ml each",
    route: "Intradermal",
    site: "Right Upper Arm",
    notes: "Mandatory; enhances polio immunity"
  },
  {
    vaccine_id: 11,
    name: "PCV-1,2 (Pneumococcal Conjugate Vaccine)",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 1.5,
    max_age_months: 3.5,
    total_doses: 2,
    frequency: "Primary series",
    when_to_give: "6 and 14 weeks",
    dose: "0.5 ml each",
    route: "Intramuscular",
    site: "Antero-lateral mid-thigh",
    notes: "Mandatory in phased rollout; prevents pneumonia. Booster at 9-12 months"
  },
  {
    vaccine_id: 12,
    name: "Measles/MR-1 (Measles-Rubella)",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 9,
    max_age_months: 12,
    total_doses: 1,
    frequency: "Primary dose",
    when_to_give: "9-12 months (up to 5 years)",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Right Upper Arm",
    notes: "Mandatory; phased in some states (e.g., Karnataka, Tamil Nadu)"
  },

  // 1-5 YEARS VACCINES
  {
    vaccine_id: 13,
    name: "DPT Booster-1",
    type: "Mandatory",
    category: "Child",
    sub_category: "Mandatory",
    min_age_months: 16,
    max_age_months: 24,
    total_doses: 1,
    frequency: "First booster",
    when_to_give: "16-24 months",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Antero-lateral mid-thigh",
    notes: "Mandatory"
  },
  {
    vaccine_id: 14,
    name: "Measles/MR-2",
    type: "Mandatory",
    category: "Child",
    sub_category: "Mandatory",
    min_age_months: 16,
    max_age_months: 24,
    total_doses: 1,
    frequency: "Second dose",
    when_to_give: "16-24 months",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Right Upper Arm",
    notes: "Mandatory; phased"
  },
  {
    vaccine_id: 15,
    name: "OPV Booster",
    type: "Mandatory",
    category: "Child",
    sub_category: "Mandatory",
    min_age_months: 16,
    max_age_months: 24,
    total_doses: 1,
    frequency: "Booster",
    when_to_give: "16-24 months",
    dose: "2 drops",
    route: "Oral",
    site: "Oral",
    notes: "Mandatory"
  },
  {
    vaccine_id: 16,
    name: "JE-2",
    type: "Endemic",
    category: "Child",
    sub_category: "High-risk",
    min_age_months: 16,
    max_age_months: 24,
    total_doses: 1,
    frequency: "Second dose",
    when_to_give: "16-24 months",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Left Upper Arm",
    notes: "In endemic areas"
  },
  {
    vaccine_id: 17,
    name: "Vitamin A (Doses 2-9)",
    type: "Mandatory",
    category: "Child",
    sub_category: "Supplement",
    min_age_months: 9,
    max_age_months: 60,
    total_doses: 8,
    frequency: "Every 6 months up to 5 years",
    when_to_give: "Every 6 months up to 5 years",
    dose: "2 ml (2 lakh IU) each",
    route: "Oral",
    site: "Oral",
    notes: "Mandatory; total 9 doses"
  },
  {
    vaccine_id: 18,
    name: "DPT Booster-2",
    type: "Mandatory",
    category: "Child",
    sub_category: "Mandatory",
    min_age_months: 60,
    max_age_months: 72,
    total_doses: 1,
    frequency: "Second booster",
    when_to_give: "5-6 years",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Mandatory"
  },
  {
    vaccine_id: 19,
    name: "MMR (IAP)",
    type: "Optional",
    category: "Child",
    sub_category: "Optional",
    min_age_months: 15,
    max_age_months: 18,
    total_doses: 1,
    frequency: "IAP recommends",
    when_to_give: "15 months",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "IAP recommends"
  },

  // 6-18 YEARS VACCINES
  {
    vaccine_id: 20,
    name: "Tdap/Td",
    type: "Mandatory",
    category: "Adolescent",
    sub_category: "Mandatory",
    min_age_months: 120,
    max_age_months: 192,
    total_doses: 2,
    frequency: "At 10 and 16 years",
    when_to_give: "10 years and 16 years",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Mandatory Td at 10/16; IAP recommends Tdap for pertussis"
  },
  {
    vaccine_id: 21,
    name: "HPV",
    type: "Optional",
    category: "Adolescent",
    sub_category: "Optional",
    min_age_months: 108,
    max_age_months: 168,
    total_doses: 2,
    frequency: "2 doses, 6 months apart",
    when_to_give: "9-14 years (boys/girls)",
    dose: "0.5 ml (2 doses, 6 months apart)",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "IAP recommends 9vHPV; 3 doses if >15 years or immunocompromised"
  },
  {
    vaccine_id: 22,
    name: "Typhoid (IAP Optional)",
    type: "Optional",
    category: "Adolescent",
    sub_category: "Optional",
    min_age_months: 72,
    max_age_months: 1200,
    total_doses: null,
    frequency: "Booster every 3 years",
    when_to_give: "Booster every 3 years",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Conjugate vaccine preferred"
  },
  {
    vaccine_id: 23,
    name: "Influenza (Annual)",
    type: "Optional",
    category: "Adolescent",
    sub_category: "Annual",
    min_age_months: 6,
    max_age_months: 1200,
    total_doses: null,
    frequency: "Annually",
    when_to_give: "Annually",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Recommended for high-risk"
  },

  // 18-60 YEARS VACCINES
  {
    vaccine_id: 24,
    name: "Td/Tdap Booster",
    type: "Mandatory",
    category: "Adult",
    sub_category: "Mandatory",
    min_age_months: 216,
    max_age_months: 720,
    total_doses: null,
    frequency: "Every 10 years",
    when_to_give: "Every 10 years",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Recommended; Tdap once in adulthood for pertussis"
  },
  {
    vaccine_id: 25,
    name: "Influenza (Adult)",
    type: "Mandatory",
    category: "Adult",
    sub_category: "Annual",
    min_age_months: 216,
    max_age_months: 720,
    total_doses: null,
    frequency: "Annually",
    when_to_give: "Annually",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "For all, especially >50 or with risks (e.g., diabetes)"
  },
  {
    vaccine_id: 26,
    name: "Pneumococcal (PCV13/PCV15 + PPSV23)",
    type: "High-risk",
    category: "Adult",
    sub_category: "High-risk",
    min_age_months: 228,
    max_age_months: 768,
    total_doses: 2,
    frequency: "Once at 19-64 if high-risk",
    when_to_give: "Once at 19-64 if high-risk (e.g., smokers, chronic illness)",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Sequential; for immunocompromised or chronic conditions"
  },
  {
    vaccine_id: 27,
    name: "HPV (Adult)",
    type: "Optional",
    category: "Adult",
    sub_category: "Optional",
    min_age_months: 216,
    max_age_months: 540,
    total_doses: 3,
    frequency: "Up to 26 years (males), 45 years (females) if not vaccinated",
    when_to_give: "Up to 26 years (males), 45 years (females) if not vaccinated",
    dose: "0.5 ml (3 doses)",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "2 doses if started 9-14"
  },

  // 60+ YEARS VACCINES
  {
    vaccine_id: 28,
    name: "Influenza (Elderly)",
    type: "Mandatory",
    category: "Elderly",
    sub_category: "Mandatory",
    min_age_months: 720,
    max_age_months: 1200,
    total_doses: null,
    frequency: "Annually",
    when_to_give: "Annually",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Strongly recommended for all >60"
  },
  {
    vaccine_id: 29,
    name: "Pneumococcal (PCV13/PCV15 + PPSV23) - Elderly",
    type: "Mandatory",
    category: "Elderly",
    sub_category: "Mandatory",
    min_age_months: 780,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "Once at >65; booster if needed",
    when_to_give: "Once at >65; booster if needed",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "For all; revaccinate PPSV23 after 5 years if high-risk"
  },
  {
    vaccine_id: 30,
    name: "Herpes Zoster (Shingles)",
    type: "Optional",
    category: "Elderly",
    sub_category: "Optional",
    min_age_months: 600,
    max_age_months: 1200,
    total_doses: 2,
    frequency: ">50 years (once)",
    when_to_give: ">50 years (once)",
    dose: "0.5 ml (2 doses, 2-6 months apart)",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Recommended for immunocompetent; prevents post-herpetic neuralgia"
  },

  // TRAVEL VACCINES
  {
    vaccine_id: 31,
    name: "Yellow Fever (YF)",
    type: "Travel",
    category: "Travel",
    sub_category: "Mandatory",
    min_age_months: 9,
    max_age_months: 1200,
    total_doses: 1,
    frequency: "One time",
    when_to_give: "At least 10 days before travel to endemic countries",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Deltoid",
    notes: "Required for entry into many endemic countries (Yellow Card certificate)"
  },
  {
    vaccine_id: 32,
    name: "Meningococcal (Quadrivalent ACWY)",
    type: "Travel",
    category: "Travel",
    sub_category: "Mandatory",
    min_age_months: 9,
    max_age_months: 1200,
    total_doses: 1,
    frequency: "One time (booster after 3–5 years if risk persists)",
    when_to_give: "At least 10 days before Hajj/Umrah or travel to high-risk areas",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Compulsory for pilgrims to Saudi Arabia (Hajj/Umrah)"
  },
  {
    vaccine_id: 33,
    name: "Polio (Travel)",
    type: "Travel",
    category: "Travel",
    sub_category: "Mandatory",
    min_age_months: 0,
    max_age_months: 1200,
    total_doses: 1,
    frequency: "Required for travel to/from countries with ongoing transmission",
    when_to_give: "Some destinations require proof of an Oral Polio Vaccine (OPV) or Inactivated Polio Vaccine (IPV) booster within 12 months to 4 weeks before travel",
    dose: "2 drops (OPV) or 0.5 ml (IPV)",
    route: "Oral or Intramuscular",
    site: "Oral or Deltoid",
    notes: "India is polio-free. Required for Hajj/Umrah: Mandatory OPV/IPV at least 6 weeks before visa application"
  },

  // HIGH-RISK VACCINES
  {
    vaccine_id: 34,
    name: "Hepatitis B (High-risk)",
    type: "High-risk",
    category: "Adult",
    sub_category: "High-risk",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 3,
    frequency: "If unvaccinated/high-risk (e.g., healthcare workers, travelers)",
    when_to_give: "If unvaccinated/high-risk (e.g., healthcare workers, travelers)",
    dose: "0.5 ml (3 doses)",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Risk groups include Dialysis patients, drug users, and individuals with multiple partners"
  },
  {
    vaccine_id: 35,
    name: "Hepatitis A (High-risk)",
    type: "High-risk",
    category: "Adult",
    sub_category: "High-risk",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "High-risk (e.g., travelers, individuals with liver disease)",
    when_to_give: "High-risk (e.g., travelers, individuals with liver disease)",
    dose: "0.5 ml (2 doses)",
    route: "Intramuscular",
    site: "Upper Arm",
    notes: "Vaccination is not universal due to endemicity"
  },
  {
    vaccine_id: 36,
    name: "MMR (High-risk)",
    type: "High-risk",
    category: "Adult",
    sub_category: "High-risk",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "If no evidence of immunity",
    when_to_give: "If no evidence of immunity",
    dose: "0.5 ml (1-2 doses)",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "Recommended for outbreaks or travel"
  },
  {
    vaccine_id: 37,
    name: "Varicella (Chickenpox)",
    type: "High-risk",
    category: "Adult",
    sub_category: "High-risk",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "If no prior infection",
    when_to_give: "If no prior infection",
    dose: "0.5 ml (2 doses)",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "Recommended for susceptible adults"
  },
  {
    vaccine_id: 38,
    name: "Cholera (Oral)",
    type: "High-risk",
    category: "Adult",
    sub_category: "High-risk",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "Endemic areas or outbreaks",
    when_to_give: "Endemic areas or outbreaks",
    dose: "Varies (oral)",
    route: "Oral",
    site: "Oral",
    notes: "High-risk only; not routine"
  }
];