export const VACCINES_TABLE = 'vaccines';

export const VACCINES_SCHEMA = `
  CREATE TABLE IF NOT EXISTS ${VACCINES_TABLE} (
    vaccine_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL,
    sub_category VARCHAR(50) NOT NULL,
    min_age_months INT NOT NULL DEFAULT 0,
    max_age_months INT NULL,
    total_doses INT NULL,
    frequency VARCHAR(200) NOT NULL,
    when_to_give TEXT NULL,
    dose VARCHAR(200) NULL,
    route VARCHAR(100) NULL,
    site VARCHAR(150) NULL,
    notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    INDEX idx_vaccine_name (name),
    INDEX idx_vaccine_type (type),
    INDEX idx_vaccine_category (category),
    INDEX idx_vaccine_sub_category (sub_category),
    INDEX idx_age_range (min_age_months, max_age_months)
  )
`;

export const VACCINES_FIELDS = {
  VACCINE_ID: 'vaccine_id',
  NAME: 'name',
  TYPE: 'type',
  CATEGORY: 'category',
  SUB_CATEGORY: 'sub_category',
  MIN_AGE_MONTHS: 'min_age_months',
  MAX_AGE_MONTHS: 'max_age_months',
  TOTAL_DOSES: 'total_doses',
  FREQUENCY: 'frequency',
  WHEN_TO_GIVE: 'when_to_give',
  DOSE: 'dose',
  ROUTE: 'route',
  SITE: 'site',
  NOTES: 'notes',
  CREATED_AT: 'created_at',
  UPDATED_AT: 'updated_at',
  IS_ACTIVE: 'is_active'
};

export const VACCINES_DATA = [
  {
    vaccine_id: 1,
    name: "BCG",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 0,
    max_age_months: 12,
    total_doses: 1,
    frequency: "One time",
    when_to_give: "At birth or as early as possible till 1 year",
    dose: "0.1 ml (0.05 ml if age < 1 month)",
    route: "Intradermal",
    site: "Left Upper Arm",
    notes: "Prevents severe forms of childhood TB"
  },
  {
    vaccine_id: 2,
    name: "Hepatitis B",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 0,
    max_age_months: 6,
    total_doses: 4,
    frequency: "Primary series",
    when_to_give: "Birth dose within 24 hours, then at 6, 10, and 14 weeks",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Antero-lateral thigh (infants), Deltoid (older children/adults)",
    notes: "Birth dose is critical for prevention of perinatal transmission"
  },
  {
    vaccine_id: 3,
    name: "OPV (Polio)",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 0,
    max_age_months: 60,
    total_doses: 5,
    frequency: "Primary series + booster",
    when_to_give: "Birth (OPV-0), 6, 10, 14 weeks, booster at 16–24 months",
    dose: "2 drops",
    route: "Oral",
    site: "Oral",
    notes: "Part of national immunization program"
  },
  {
    vaccine_id: 4,
    name: "Pentavalent (DPT+HepB+Hib)",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 6,
    max_age_months: 12,
    total_doses: 3,
    frequency: "Primary series",
    when_to_give: "6, 10, and 14 weeks",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Antero-lateral mid-thigh",
    notes: "Combines DPT, Hepatitis B, and Hib in a single vaccine"
  },
  {
    vaccine_id: 5,
    name: "Rotavirus",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 6,
    max_age_months: 12,
    total_doses: 3,
    frequency: "Primary series",
    when_to_give: "6, 10, and 14 weeks",
    dose: "5 drops (depending on brand)",
    route: "Oral",
    site: "Oral",
    notes: "Protects against rotavirus diarrhea; different brands may have 2 or 3 doses"
  },
  {
    vaccine_id: 6,
    name: "fIPV (Fractional Polio)",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 6,
    max_age_months: 14,
    total_doses: 2,
    frequency: "Primary series",
    when_to_give: "6 and 14 weeks",
    dose: "0.1 ml",
    route: "Intradermal",
    site: "Right Upper Arm",
    notes: "Fractional dose given intradermally as per updated guidelines"
  },
  {
    vaccine_id: 7,
    name: "PCV (Pneumococcal)",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 6,
    max_age_months: 12,
    total_doses: 3,
    frequency: "2 doses + 1 booster",
    when_to_give: "6 and 14 weeks, booster at 9 months",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Antero-lateral thigh",
    notes: "Protects against pneumococcal diseases like meningitis and pneumonia"
  },
  {
    vaccine_id: 8,
    name: "Measles/MR",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Mandatory",
    min_age_months: 9,
    max_age_months: 24,
    total_doses: 2,
    frequency: "Two doses",
    when_to_give: "9–12 months and 16–24 months",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Right Upper Arm",
    notes: "Second dose is essential for complete protection"
  },
  {
    vaccine_id: 9,
    name: "Vitamin A",
    type: "Mandatory",
    category: "Infant",
    sub_category: "Supplement",
    min_age_months: 9,
    max_age_months: 60,
    total_doses: 9,
    frequency: "Every 6 months until 5 years",
    when_to_give: "First dose at 9 months with measles/MR, then every 6 months",
    dose: "1 ml (1 lakh IU for <1 year, 2 lakh IU thereafter)",
    route: "Oral",
    site: "Oral",
    notes: "Given till 5 years of age"
  },
  {
    vaccine_id: 10,
    name: "Typhoid Conjugate",
    type: "Optional",
    category: "Infant",
    sub_category: "Optional",
    min_age_months: 6,
    max_age_months: 9,
    total_doses: 1,
    frequency: "One time",
    when_to_give: "6–9 months",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Antero-lateral thigh",
    notes: "Recommended in private sector immunization"
  },
  {
    vaccine_id: 11,
    name: "JE (Japanese Encephalitis)",
    type: "Endemic",
    category: "Child",
    sub_category: "High-risk",
    min_age_months: 9,
    max_age_months: 24,
    total_doses: 2,
    frequency: "Two doses in endemic areas",
    when_to_give: "First dose at 9 months, second dose at 16–24 months",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "Given in JE endemic districts only"
  },
  {
    vaccine_id: 12,
    name: "Influenza (Children)",
    type: "Mandatory",
    category: "Child",
    sub_category: "Annual",
    min_age_months: 6,
    max_age_months: 1200,
    total_doses: null,
    frequency: "Annual",
    when_to_give: "Every year starting from 6 months of age",
    dose: "0.25–0.5 ml depending on age",
    route: "Intramuscular",
    site: "Deltoid (children/adults), Antero-lateral thigh (infants)",
    notes: "Annual vaccination recommended"
  },
  {
    vaccine_id: 13,
    name: "DPT Booster",
    type: "Mandatory",
    category: "Child",
    sub_category: "Booster",
    min_age_months: 16,
    max_age_months: 72,
    total_doses: 2,
    frequency: "Two boosters",
    when_to_give: "First booster at 16–24 months, second booster at 4–6 years",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid or thigh",
    notes: "Important to maintain immunity in early childhood"
  },
  {
    vaccine_id: 14,
    name: "Hepatitis A (Children)",
    type: "Optional",
    category: "Child",
    sub_category: "Optional",
    min_age_months: 12,
    max_age_months: 23,
    total_doses: 2,
    frequency: "Two doses",
    when_to_give: "First dose at 12 months, second dose 6–12 months later",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Protects against Hepatitis A infection"
  },
  {
    vaccine_id: 15,
    name: "MMR (Measles, Mumps, Rubella)",
    type: "Optional",
    category: "Child",
    sub_category: "Optional",
    min_age_months: 15,
    max_age_months: 60,
    total_doses: 2,
    frequency: "Two doses",
    when_to_give: "First dose at 15 months, second dose at 4–6 years",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "Second dose ensures protection against all three diseases"
  },
  {
    vaccine_id: 16,
    name: "Varicella (Chickenpox)",
    type: "Optional",
    category: "Child",
    sub_category: "Optional",
    min_age_months: 15,
    max_age_months: 72,
    total_doses: 2,
    frequency: "Two doses",
    when_to_give: "First dose at 15–18 months, second dose at 4–6 years",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "Protects against chickenpox and its complications"
  },
  {
    vaccine_id: 17,
    name: "Typhoid Booster",
    type: "Optional",
    category: "Child",
    sub_category: "Booster",
    min_age_months: 72,
    max_age_months: 1200,
    total_doses: null,
    frequency: "Every 3 years",
    when_to_give: "Every 3 years after primary Typhoid conjugate vaccine",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Needed to maintain typhoid protection"
  },
  {
    vaccine_id: 18,
    name: "HPV (Human Papillomavirus)",
    type: "Optional",
    category: "Adolescent",
    sub_category: "Optional",
    min_age_months: 108,
    max_age_months: 540,
    total_doses: 2,
    frequency: "2 doses (9–14 yrs) or 3 doses (>15 yrs)",
    when_to_give: "Girls 9–14 yrs: 2 doses 6 months apart; >15 yrs: 3 doses (0,1,6 months)",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Prevents cervical cancer and HPV-related diseases"
  },
  {
    vaccine_id: 19,
    name: "Td/Tdap (Adolescents)",
    type: "Mandatory",
    category: "Adolescent",
    sub_category: "Mandatory",
    min_age_months: 120,
    max_age_months: 192,
    total_doses: 2,
    frequency: "At 10 and 16 years",
    when_to_give: "First at 10 years, second at 16 years",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Protects against tetanus, diphtheria, and pertussis in adolescence"
  },
  {
    vaccine_id: 20,
    name: "Cholera (Oral)",
    type: "High-risk",
    category: "Adolescent",
    sub_category: "Event-based",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "Outbreak only",
    when_to_give: "During outbreaks or high-risk exposure",
    dose: "2 doses (1–6 weeks apart)",
    route: "Oral",
    site: "Oral",
    notes: "Used only in outbreak or high-risk situations"
  },
  {
    vaccine_id: 21,
    name: "Hepatitis A (Adults)",
    type: "High-risk",
    category: "Adult",
    sub_category: "Optional",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "Two doses",
    when_to_give: "First dose at any time, second dose 6–12 months later",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Recommended for high-risk adults and travelers"
  },
  {
    vaccine_id: 22,
    name: "Hepatitis B (Adults)",
    type: "High-risk",
    category: "Adult",
    sub_category: "Optional",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 3,
    frequency: "Primary series for unvaccinated",
    when_to_give: "0, 1, and 6 months schedule",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Important for healthcare workers and high-risk adults"
  },
  {
    vaccine_id: 23,
    name: "MMR (Adults)",
    type: "Catch-up",
    category: "Adult",
    sub_category: "Catch-up",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "One or two doses if not immune",
    when_to_give: "One dose if previously received; two doses 4 weeks apart if unvaccinated",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "Recommended for adults without documented immunity"
  },
  {
    vaccine_id: 24,
    name: "Td/Tdap Booster (Adults)",
    type: "Mandatory",
    category: "Adult",
    sub_category: "Booster",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: null,
    frequency: "Every 10 years",
    when_to_give: "Every 10 years after primary schedule",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Maintains protection against tetanus and diphtheria"
  },
  {
    vaccine_id: 25,
    name: "Varicella (Adults)",
    type: "Catch-up",
    category: "Adult",
    sub_category: "Catch-up",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "Two doses if not immune",
    when_to_give: "Two doses at least 4–8 weeks apart",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "For adults without prior history of chickenpox or vaccination"
  },
  {
    vaccine_id: 26,
    name: "Pneumococcal (Adults)",
    type: "High-risk",
    category: "Adult",
    sub_category: "High-risk",
    min_age_months: 228,
    max_age_months: 780,
    total_doses: 2,
    frequency: "One time + booster after 5 years",
    when_to_give: "First dose at any time after 19 years in high-risk adults, booster after 5 years",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Protects adults at high risk of pneumococcal disease"
  },
  {
    vaccine_id: 27,
    name: "Herpes Zoster (Shingles)",
    type: "Optional",
    category: "Elderly",
    sub_category: "Optional",
    min_age_months: 600,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "One time (2 doses, 2–6 months apart)",
    when_to_give: "After age 50–60 years, 2 doses given 2–6 months apart",
    dose: "0.5 ml",
    route: "Subcutaneous or Intramuscular (brand-specific)",
    site: "Deltoid",
    notes: "Prevents shingles and post-herpetic neuralgia"
  },
  {
    vaccine_id: 28,
    name: "Hepatitis B (Elderly, High-risk)",
    type: "High-risk",
    category: "Elderly",
    sub_category: "High-risk",
    min_age_months: 720,
    max_age_months: 1200,
    total_doses: 3,
    frequency: "Primary series if unvaccinated",
    when_to_give: "0, 1, and 6 months if not previously vaccinated",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Important for elderly in high-risk groups like diabetics, CKD, healthcare workers"
  },
  {
    vaccine_id: 29,
    name: "Influenza (Elderly)",
    type: "Mandatory",
    category: "Elderly",
    sub_category: "Annual",
    min_age_months: 720,
    max_age_months: 1200,
    total_doses: null,
    frequency: "Annual",
    when_to_give: "Every year after 60 years of age",
    dose: "0.5 ml (high-dose for elderly preferred)",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Recommended annually for elderly due to high risk"
  },
  {
    vaccine_id: 30,
    name: "Td/Tdap Booster (Elderly)",
    type: "Mandatory",
    category: "Elderly",
    sub_category: "Booster",
    min_age_months: 720,
    max_age_months: 1200,
    total_doses: null,
    frequency: "Every 10 years",
    when_to_give: "Every 10 years after age 60",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Maintains tetanus and diphtheria immunity in elderly"
  },
  {
    vaccine_id: 31,
    name: "Pneumococcal (Elderly)",
    type: "Mandatory",
    category: "Elderly",
    sub_category: "Mandatory",
    min_age_months: 780,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "One time + booster after 5 years",
    when_to_give: "After age 65 years, one dose and booster after 5 years",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Protects against pneumonia, meningitis, and sepsis in elderly"
  },
  {
    vaccine_id: 32,
    name: "Yellow Fever (YF)",
    type: "Travel",
    category: "Travel",
    sub_category: "Mandatory",
    min_age_months: 9,
    max_age_months: 1200,
    total_doses: 1,
    frequency: "One time",
    when_to_give: "At least 10 days before travel to endemic countries",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Deltoid",
    notes: "Required for entry into many endemic countries (Yellow Card certificate)"
  },
  {
    vaccine_id: 33,
    name: "Meningococcal (Quadrivalent ACWY)",
    type: "Travel",
    category: "Travel",
    sub_category: "Mandatory",
    min_age_months: 9,
    max_age_months: 1200,
    total_doses: 1,
    frequency: "One time (booster after 3–5 years if risk persists)",
    when_to_give: "At least 10 days before Hajj/Umrah or travel to high-risk areas",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Compulsory for pilgrims to Saudi Arabia (Hajj/Umrah)"
  },
  {
    vaccine_id: 34,
    name: "Rabies (Post-exposure prophylaxis - PEP)",
    type: "High-risk",
    category: "Event",
    sub_category: "Post-exposure",
    min_age_months: 0,
    max_age_months: 1200,
    total_doses: null,
    frequency: "As per exposure",
    when_to_give: "Immediately after suspected/confirmed exposure (animal bite/scratch)",
    dose: "Essen regimen: 1.0 ml IM on days 0,3,7,14,28; RIG if category III exposure",
    route: "Intramuscular or Intradermal",
    site: "Deltoid or thigh (infants)",
    notes: "RIG required for severe exposures; follow national PEP guidelines"
  },
  {
    vaccine_id: 35,
    name: "Rabies (Pre-exposure prophylaxis - PrEP)",
    type: "High-risk",
    category: "Travel",
    sub_category: "Optional",
    min_age_months: 0,
    max_age_months: 1200,
    total_doses: 3,
    frequency: "Primary series",
    when_to_give: "For travelers to high-risk areas or occupational exposure",
    dose: "0.5 ml IM on days 0,7,21–28",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Reduces need for immunoglobulin if exposed later"
  },
  {
    vaccine_id: 36,
    name: "Tetanus Toxoid (TT) / Tdap in Pregnancy",
    type: "Pregnancy",
    category: "Pregnancy",
    sub_category: "Mandatory",
    min_age_months: 180,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "As per antenatal schedule",
    when_to_give: "TT-1 early in pregnancy, TT-2 after 4 weeks; Tdap once between 27–36 weeks",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Protects both mother and newborn from tetanus and pertussis"
  },
  {
    vaccine_id: 37,
    name: "COVID-19",
    type: "Event-based",
    category: "Event",
    sub_category: "Recommended",
    min_age_months: 6,
    max_age_months: 1200,
    total_doses: null,
    frequency: "As per national guidelines",
    when_to_give: "Primary series and boosters as recommended by MoHFW/WHO",
    dose: "0.2–0.5 ml depending on product",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Introduced during pandemic; updated as per government advisories"
  },
  {
    vaccine_id: 38,
    name: "Typhoid Booster (Adults)",
    type: "Optional",
    category: "Adult",
    sub_category: "Booster",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: null,
    frequency: "Every 3 years",
    when_to_give: "Every 3 years in adults at risk",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Reinforces typhoid immunity in adults"
  },
  {
    vaccine_id: 39,
    name: "MMR (Catch-up)",
    type: "Catch-up",
    category: "Catch-up",
    sub_category: "Optional",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "Catch-up if missed in childhood",
    when_to_give: "Two doses at least 4 weeks apart if unvaccinated",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "Important for adolescents/adults who missed childhood doses"
  },
  {
    vaccine_id: 40,
    name: "Varicella (Catch-up)",
    type: "Catch-up",
    category: "Catch-up",
    sub_category: "Optional",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "Catch-up if missed",
    when_to_give: "Two doses at least 4–8 weeks apart if unvaccinated",
    dose: "0.5 ml",
    route: "Subcutaneous",
    site: "Upper Arm",
    notes: "Recommended for adolescents and adults without immunity"
  },
  {
    vaccine_id: 41,
    name: "HPV (Human Papillomavirus)",
    type: "Optional",
    category: "Adolescent",
    sub_category: "Optional",
    min_age_months: 108,
    max_age_months: 540,
    total_doses: 2,
    frequency: "2 doses (9–14 yrs) or 3 doses (>15 yrs)",
    when_to_give: "First dose at 9–14 years, second after 6–12 months; if >15 yrs, 3-dose schedule",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Protects against cervical and other HPV-related cancers"
  },
  {
    vaccine_id: 42,
    name: "Herpes Zoster (Shingles)",
    type: "Optional",
    category: "Elderly",
    sub_category: "Optional",
    min_age_months: 600,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "One time (2 doses, 2–6 months apart)",
    when_to_give: "After 50 years of age",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Reduces risk of shingles and postherpetic neuralgia"
  },
  {
    vaccine_id: 43,
    name: "Cholera (Oral)",
    type: "High-risk",
    category: "Event",
    sub_category: "Outbreak",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "During outbreak only",
    when_to_give: "As advised during outbreaks in high-risk areas",
    dose: "1.5–3 ml (depending on brand)",
    route: "Oral",
    site: "Oral",
    notes: "Given during outbreaks; not part of routine immunization"
  },
  {
    vaccine_id: 44,
    name: "Hepatitis A (Adults)",
    type: "High-risk",
    category: "Adult",
    sub_category: "Optional",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 2,
    frequency: "Two doses",
    when_to_give: "First dose anytime, second dose after 6–12 months",
    dose: "0.5 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Prevents Hepatitis A infection; especially for high-risk adults"
  },
  {
    vaccine_id: 45,
    name: "Hepatitis B (Adults)",
    type: "High-risk",
    category: "Adult",
    sub_category: "Optional",
    min_age_months: 216,
    max_age_months: 1200,
    total_doses: 3,
    frequency: "Primary series for unvaccinated adults",
    when_to_give: "0, 1, and 6 months",
    dose: "1.0 ml",
    route: "Intramuscular",
    site: "Deltoid",
    notes: "Protects adults from Hepatitis B if not vaccinated in childhood"
  }
];